# Generated by Django 3.0.3 on 2020-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name', max_length=100)),
                ('email', models.EmailField(help_text='Enter the mail', max_length=100)),
                ('university', models.CharField(choices=[('ARDHI', 'Ardhi university'), ('UDSM', 'University of Dar-es-salaam'), ('KIUT', 'Kampala University'), ('CBE', 'College of Bussiness'), ('ATC', 'Arusha Technicall college'), ('SUA', 'Saut University'), ('SOKOINE', 'Sokoine University'), ('UDOM', 'University of Dodoma'), ('DIT', 'Dar-es-salaam institute of technology'), ('TUM', 'Tumaini University'), ('DUCE', 'Duce University')], default='CBE', max_length=10)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
