# Generated by Django 3.0.3 on 2020-10-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='university',
            field=models.CharField(choices=[('DIT', 'Dar-es-salaam institute of technology'), ('ARDHI', 'Ardhi university'), ('UDSM', 'University of Dar-es-salaam'), ('KIUT', 'Kampala University'), ('CBE', 'College of Bussiness'), ('ATC', 'Arusha Technicall college'), ('SUA', 'Saut University'), ('SOKOINE', 'Sokoine University'), ('UDOM', 'University of Dodoma'), ('TUM', 'Tumaini University'), ('DUCE', 'Duce University')], default='CBE', max_length=10),
        ),
    ]
